site_name: Eigerlang Documentation
repo_url: https://github.com/eigerproject/eigerlang
repo_name: eigerproject/eigerlang


markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ru
          name: Русский
          build: true
        - locale: hy
          name: Հայերեն
          build: true

extra_css:
  - 'overrides/extra.css'

extra_javascript:
  - 'overrides/eiger-highlight.js'

extra:
    alternate:
      - name: English
        link: /
        lang: en
        flag: test
      - name: Русский
        link: /ru/
        lang: ru
      - name: Հայերեն
        link: /hy/
        lang: hy
theme:
  name: material
  logo: ./logo.png

  features:
    - content.code.copy
    - content.code.annotate 
  font:
    text: Noto
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      accent: custom